[package]
name = "wasi-nn-onnx"
version = "0.1.0"
authors = ["Radu M <root@radu.sh>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
futures = "0.3"
http = "0.2"
log = { version = "0.4", default-features = false }
reqwest = { version = "0.11", default-features = true, features = ["json", "blocking"] }
structopt = "0.3.21"
thiserror = "1.0"
tokio = { version = "1.4.0", features = ["full"] }
wasmtime = "0.28"
wasmtime-runtime = "0.28"
wasmtime-wasi = "0.28"
wasi-common = "0.28"
wasi-cap-std-sync = "0.28"
wasi-experimental-http-wasmtime = "0.5"
wiggle =  "0.28"

[[bin]]
name = "wasmtime-onnx"
path = "bin/wasmtime-onnx.rs"
