[package]
name = "wasi-nn-onnx-wasmtime"
version = "0.1.0"
authors = ["Radu M <root@radu.sh>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
byteorder = "1.4"
futures = "0.3"
http = "0.2"
log = { version = "0.4", default-features = false }
env_logger = "0.8"
onnxruntime = { git = "https://github.com/radu-matei/onnxruntime-rs", branch = "owned-session" }
reqwest = { version = "0.11", default-features = true, features = ["json", "blocking"] }
structopt = "0.3.21"
thiserror = "1.0"
tokio = { version = "1.4.0", features = ["full"] }
tracing = "0.1"
wasmtime = "0.28"
wasmtime-runtime = "0.28"
wasmtime-wasi = "0.28"
wasi-common = "0.28"
wasi-cap-std-sync = "0.28"
wiggle =  "0.28"
