[package]
name = "wasi-nn-onnx-wasmtime"
version = "0.1.0"
authors = ["Radu M <root@radu.sh>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
byteorder = "1.4"
log = { version = "0.4", default-features = false }
onnxruntime = { git = "https://github.com/radu-matei/onnxruntime-rs", branch = "owned-session" }
thiserror = "1.0"
wasmtime = "0.28"
wasmtime-runtime = "0.28"
wasmtime-wasi = "0.28"
wasi-common = "0.28"
wasi-cap-std-sync = "0.28"
wiggle =  "0.28"
