name: Rust
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: rustup target add wasm32-wasi && cargo build
      - name: Run simple test
        run: RUST_LOG=wasi_nn_onnx_wasmtime=info,integration=info cargo test --all --all-features -- --nocapture
